增加安装JDK的脚本

diff --git a/home_bin/xinstall b/home_bin/xinstall
--- a/home_bin/xinstall
+++ b/home_bin/xinstall
@@ -4,8 +4,8 @@ APP=('redis' 'jdk' 'svn')
 PATTEN=("redis.*" "^jdk*" "^svn*")
 APPDIR=
 INDEX=
-URL=('http://download.redis.io/releases/redis-3.0.0.tar.gz' '')
-INSTALL_FUN=(install_redis '' install_svn)
+URL=('http://download.redis.io/releases/redis-3.0.0.tar.gz' 'http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz' '[ERROR:svn]')
+INSTALL_FUN=(install_redis install_jdk install_svn)
 DEF_PROFILE='~/.bashrc'
 DEF_INSDIR='.'
 
@@ -39,6 +39,34 @@ if [ 0 -eq $? ]; then
     echo "install redis: DONE!"
 else
     echo "install redis: FAILED!"
+    exit 1
+fi
+}
+
+# 安装JDK
+function install_jdk {
+PKG='jdk-7u79-linux-x64.tar.gz'
+PST='jdk1.7.0_79'
+INSDIR=${1:-$DEF_INSDIR}
+PROFILE=${2:-$DEF_PROFILE}
+echo "install jdk: $INSDIR $PROFILE"
+
+if [ -e $PST ]; then
+    echo "install failed: jdk exists."
+    exit 1
+fi
+
+# 如果目录不存在，则解压
+xtar -x -f $PKG -d $INSDIR
+echo "# INSTALL_JDK_DONE" >> $PROFILE  \
+&& echo "export JAVA_HOME=$PWD/$INSDIR/$PST" >> $PROFILE && \
+&& echo "export PATH=\$PATH:\$JAVA_HOME/bin" >> $PROFILE   \
+&& source $PROFILE
+
+if [ 0 -eq $? ]; then
+    echo "install jdk: DONE!"
+else
+    echo "install jdk: FAILED!"
     exit 1
 fi
 }
